# Cache static assets (CSS, JS, images, etc.) for a year
[[headers]]
  for = "/**"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

# Set shorter caching for HTML files
[[headers]]
  for = "/*.html"
  [headers.values]
  Cache-Control = "no-cache"