backend:
  name: git-gateway
  branch: main
  # squash_merges: true

# https://decapcms.org/docs/working-with-a-local-git-repository/
# npx decap-server
local_backend: true

# publish_mode: editorial_workflow
site_url: https://danceophile.com
media_folder: /src/images/gallery/
# public_folder: /static/images/gallery/

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog" # Folder where content is stored
    create: true
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "body", label: "Body", widget: "markdown" }