# https://docs.astro.build/en/guides/cms/decap-cms/
backend:
  name: git-gateway
  branch: main
  # squash_merges: true

# https://decapcms.org/docs/working-with-a-local-git-repository/
# npx decap-server
local_backend: true

# publish_mode: editorial_workflow
site_url: https://danceophile.com
media_folder: "src/images/gallery" # Location where files will be stored in the repo
public_folder: "src/images/gallery" # The src attribute for uploaded media

collections:
  - name: "events" # Used in routes, e.g., /admin/collections/blog
    label: "Events" # Used in the UI
    folder: "src/content/events" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in frontmatter
      # https://decapcms.org/docs/widgets/
      - label: "Event Name"
        name: "title"
        widget: "string"
      - label: "Event Date"
        name: "date"
        widget: "datetime"
        date_format: "YYYY-MM-DD"
        default: ""
      - label: Start Time
        name: "start"
        widget: "datetime"
        time_format: "h:mm A"
      - label: End Time
        name: "end"
        widget: "datetime"
        time_format: "h:mm A"
        required: false
      - label: "Event Description"
        name: "description"
        widget: "string"
        date_format: "YYYY-MM-DD"
        required: false
